### ISSUE TITLE
[apiman] SSO does not work when accessing apiman from OSE console

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#177] opened 2016-01-27 13:05 UTC

**Comment by KurtStam** [comment] 2016-02-08 18:36
@jpechane what link are you using? The one from the generic service listing in openshift?

**Comment by jpechane** [comment] 2016-02-09 04:08
Yes

**Comment by KurtStam** [comment] 2016-02-09 18:12
This one will take a bit to address, and really it's on the OpenShift console to address, where the issue is that the AuthToken needs to be put on the link so it can be passed into Apiman. This really shows that our current SSO solution really is very brittle. I will try to see if I can get to work better, but it may take a bit.

**Comment by KurtStam** [comment] 2016-03-09 18:49
Small update, it does work from the OpenShift console now, after going into apiman via the fabric8 console first. Soon an OpenShift plugin on the UI side will deliver the final fix for this.

**Comment by KurtStam** [comment] 2016-03-31 13:09
@gashcrumb is working on the integration with the openshift console, which should address this issue.

**Comment by KurtStam** [comment] 2016-04-05 23:25
@gashcrumb You can now run the apiman-console on SSL: 
https://github.com/fabric8io/fabric8-ipaas/issues/274 

It still is not the default, but we may want to run the fabric8-console on SSL too, and then switch the default to be SSL.

**Comment by gashcrumb** [comment] 2016-04-06 10:35
Yay!  Will give it a go today...

**Comment by KurtStam** [comment] 2016-04-09 18:22
Hi Stan, I added support to POST to /apimanui/link, with an 'access_token' and a 'redirect' URL containing a link into the apiman console, see issue #287. I also added https://github.com/fabric8io/fabric8-ipaas/blob/master/apiman/test-apiman-linking.html
for testing purposes.

**Closed** 2016-06-03 13:01 UTC
Labels: api-management, bug
